name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ECR_ACCOUNT_URL: public.ecr.aws/f5f5j0q9
  ECS_CLUSTER: testx
  ECS_SERVICE: khaitest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Authenticate Docker client to ECR Public registry
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_ACCOUNT_URL }}

      - name: build and push docker image
        env:
          CI: true
          AWS_ECR_ACCOUNT_URL: ${{ env.AWS_ECR_ACCOUNT_URL }}
        run: |
          COMMIT_AUTHOR=`git log -1 --pretty=format:'%an'`
          COMMIT_MESSAGE=`git log -1 --pretty=%B`
          docker build -t my-node-app .
          docker tag my-node-app public.ecr.aws/f5f5j0q9/my-node-app:latest
          docker push public.ecr.aws/f5f5j0q9/my-node-app:latest
